### PR TITLE
RPC-JSON

### PR DESCRIPTION
**Pull request by FLYBYME**
I've added an RPC-JSON style calling. Would like ti to be sent up stream.

Play around with it for a bit. I'm open to ideas.

### CODE REVIEW

**Comment by devdazed** [comment]
do you think it would be a better idea to have the events and all the rest of the system use the RPC as a layer of communication with the peers.  so basically everything would use RPC as the layer.

**Comment by FLYBYME** [comment]
I think that the rpc layer could go lower in the stack. If the rpc layer knew more about the servent ie:(the peers that are in the network) could be very powerful. I don't think that the core system should using the rpc layer for communication.

I re-factored the code so many time trying to get a good fit. Take a look at past code from https://github.com/FLYBYME/rpc-socket
If you take a look at https://github.com/FLYBYME/rpc-socket/blob/devel/lib/socket.js#L34 you will see that i had a very similar way of dealing with events on the core layer.

I do think that the rpc layer could be more snug with the core system. The problem i see is that the rpc layer knows nothing of the core system or of the network that it is part of. For the rpc layer to be aware of other peers would make the rpc layer seem less isolated.

Something I have though of is some sort of routing protocol (Like “Open Shortest Path First”). So what would happen is not every peers would need to be connected to each other. Maybe a node and supernode style system. You would route rpc query's through what ever supernode’s you are connected to.

I am open to any ideas, and I would like to see where this goes.

Tim.

**Comment by devdazed** [comment]
this sounds good.  about the supernode idea.  I think that supernodes would only be required if there are hundreds of nodes.  the tcp connections are pretty lightweight and can handle a bit.  what is you thinking on this?  how would the node know if it is a supernode or not?

**Comment by FLYBYME** [comment]
I don't know what the best way to do the supernode thing. I have played around with code but have not come up with anything that fits.

take a look at this. kinda how I'm using the code.
network.js
https://gist.github.com/1411962
rpc.js
https://gist.github.com/1411970

Oh and take a look at this.
You can see how I was thinking of doing the routing.
https://gist.github.com/1255016

**Comment by devdazed** [comment]
cool, we'll start with this and build off of it

**Pull request merged**
